apiVersion: v1 # Kubernetes API version for core resources like Service
kind: Service # Defines a Service, which exposes Pods to the network
metadata:
  name: python-service # Name of the Service, used to reference it within the cluster
spec:
  type: NodePort # Service type that exposes the Service on each Node's IP at a static port
  selector:
    app: python-app # Selects Pods with label 'app:  python-app' to route traffic to
  ports:
    - port: 8000 # The port on the Service itself (cluster-internal). Other Pods in the cluster can use this port to reach the Service
      targetPort: 8000 # The port on the Pod/container that the Service will forward traffic to. In this case, the app is listening on port 5000 inside the container
      nodePort: 30050 # The port on each Nodeâ€™s IP where this Service is exposed externally. Allows access to the Service from outside the cluster