apiVersion: v1
kind: Service
metadata:
  name: order-worker
  namespace: webapp-mq
spec:
  selector:
    app: order-worker
  type: NodePort
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      nodePort: 30060